class Parent {
	Parent(){System.out.println("Parent class 0-arg  constructor");}
}
class Child extends Parent{
/* default code generated by compiler
Child(){
    super();
} 

*/
	
	public static void main(String[] args) {
		new Child();
		
	}
}