// This will raise a error becauze here super() keyword generated by compiler but no O-arg constructor present in Parent class
class Parent {
	Parent(int a){System.out.println("Parent class 1-arg  constructor");}
}
class Child extends Parent{
	//super(); compiler generated code
	Child()
	{
		System.out.println("Child class 0-arg  constructor");
	}
	Child(int a)
	{
		//super(); compiler generated code
		System.out.println("Child class 1-arg  constructor");
	}
	
	public static void main(String[] args) {
		new Child();
		new Child(10);
	}
}

