// In below expected output should be "Child class 0-arg  constructor". but out here is different.
class Parent {
	Parent(){System.out.println("Parent class 0-arg  constructor");}
}
class Child extends Parent{
	//super(); code is generated by compiler
	Child()
	{
		System.out.println("Child class 0-arg  constructor");
	}
	
	public static void main(String[] args) {
		new Child();
		
	}
}