class Parent {
	{System.out.println("Parent class instance block");}
	super();//code is generated by compiler
	Parent(){
		System.out.println("Parent class 0-arg constructor");
	}
}
class Child extends Parent{
	{System.out.println("Child class instance block");}
	super();// code is generated by compiler
	Child(){
		System.out.println("Child class 0-arg constructor");
	}

	public static void main(String[] args) {
		new Child();  // first instance block executed then constructor		
	}
}